### ISSUE TITLE
[FE] 헤더, 풋터 작업

### ISSUE THREAD

**Issue by JIAHLEE0213** [codestates-seb/seb45_main_004#32]
### 만들고자 하는 기능이 무엇인가요?
header, footer 컴포넌트 구현

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. Header
- [x] 로그인 미적용 시 ) 서비스 명 / 로그인버튼 / 회원가입 버튼이 렌더된다.
- [x] 로그인 적용 시 ) 서비스 명 / 파티 초대 버튼 / 알림버튼(아이콘) / 유저버튼(아이콘)이 렌더된다.

2. Footer
- [x] seb45_main_004 깃허브링크 / 개발자 명단이 렌더된다.

### 예상 작업 시간
1day

**Comment by YongILTree1** [comment]
* 상태관리 연결이 되지 않아서 로그인 상태에 따라 버튼이 자동으로 달라지지는 않음.. 로그인 상태 관리를 공부 중에 있음..
